database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: flatmatesync
  migrations_url: file://db/migrations
server:
  host: localhost
  port: 8080
oauth:
  client_id: client_id 
  client_secret: client_secret