// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Flat struct {
	ID        int32
	Name      string
	DeletedAt sql.NullTime
	CreatedAt time.Time
}

type Payment struct {
	ID          int32
	Amount      float64
	Description sql.NullString
	PayerID     int32
	FlatID      int32
	PaymentDate time.Time
	DeletedAt   sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PaymentParticipant struct {
	ID            int32
	PaymentID     int32
	ParticipantID int32
	DeletedAt     sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	Username     string
	Email        string
	PasswordHash sql.NullString
	OidcID       sql.NullString
	OidcProvider sql.NullString
	DeletedAt    sql.NullTime
	CreatedAt    time.Time
}

type UserFlat struct {
	ID        int32
	UserID    int32
	FlatID    int32
	IsAdmin   bool
	Balance   float64
	DeletedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
