// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	// Create
	CreateFlat(ctx context.Context, name string) (Flat, error)
	// Create
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Create
	CreateUserFlat(ctx context.Context, arg CreateUserFlatParams) (UserFlat, error)
	// Read
	GetFlat(ctx context.Context, id int32) (Flat, error)
	GetFlatWithUsers(ctx context.Context, id int32) ([]GetFlatWithUsersRow, error)
	// Read
	GetUser(ctx context.Context, username string) (User, error)
	// Read
	GetUserFlat(ctx context.Context, id int32) (UserFlat, error)
	// Hard Delete
	HardDeleteFlat(ctx context.Context, id int32) error
	// Hard Delete
	HardDeleteUser(ctx context.Context, username string) error
	// Hard Delete
	HardDeleteUserFlat(ctx context.Context, id int32) error
	// List with pagination
	ListFlats(ctx context.Context, arg ListFlatsParams) ([]Flat, error)
	// List with pagination
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Delete (Soft Delete)
	SoftDeleteFlat(ctx context.Context, id int32) error
	// Delete (Soft Delete)
	SoftDeleteUser(ctx context.Context, username string) error
	// Delete (Soft Delete)
	SoftDeleteUserFlat(ctx context.Context, id int32) error
	// Update
	UpdateFlat(ctx context.Context, arg UpdateFlatParams) (Flat, error)
	// Update
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// Update
	UpdateUserFlat(ctx context.Context, arg UpdateUserFlatParams) (UserFlat, error)
}

var _ Querier = (*Queries)(nil)
